name: C/C++ CI

on:
  push:
    branches: [ "master" , "main" ]
  pull_request:
    branches: [ "master" , "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make build
      run: make build
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
